#
# Module manifest for module 'Module'
#
# Generated by: José Oliveira
#
# Generated on: 05/12/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'BitbucketCLI.psm1'

# Version number of this module.
ModuleVersion = 'automatic'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '3a547d65-b705-46e3-a684-399ed3c6c8ff'

# Author of this module
Author = 'José Oliveira'

# Company or vendor of this module
CompanyName = 'Sbanken'

Descrition = 'Bitbucket Rest API Command Line Interface'

}

