name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        run: pwsh -Command 'Publish-Module -Path . -NuGetApiKey ${{ secrets.NuGetApiKey }}'