name: Publish new version
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Version (1.0)'
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: pwsh -File ./Run-Tests.ps1
      - name: Publish
        run: pwsh -Command 'Publish-Module -Path . -NuGetApiKey ${{ secrets.NuGetApiKey }} 2>&1'
      - name: Tagging
        run: git tag "v$VERSION" && git push --follow-tags